import tkinter as tk
from tkinter import*
pw=Tk()
pw.title("Perceptron")
pw.geometry('1350x750+0+0')
background_imag2 = PhotoImage(file="Percep.png")
backgrounda = Label(pw, image=background_imag2, bd=0)
backgrounda.pack()
l=Label(pw,font=('Times New Roman',25,'bold italic'),text='Perceptron Model',fg='black',bd=10,anchor='w',bg='violet')
l.place(x=550,y=30)
f1=Frame(pw,width=800,height=500,relief='sunken',bg='black')
f1.place(x=300,y=120)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='      A perceptron is a neural network unit (an artificial neuron) that ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=10)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='does certain computations to detect features or business intelligence  ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=50)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='in the input data. It is a Single Layer. It is also used in Supervised ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=90)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='learning.It also helps to classify the given input data.            ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=130)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='Since we have the electric grid dataset which is to be classified as     ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=170)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='Stable and Unstable on the given features.                               ',fg='blue',bd=10,anchor='w',bg='black')
l.place(x=5,y=210)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='Our dataset contains 14 FEATURES in which our target output is in last   ',fg='green',bd=10,anchor='w',bg='black')
l.place(x=5,y=250)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='column which is the "stabf" features which represents Stable or Unstable',fg='green',bd=10,anchor='w',bg='black')
l.place(x=5,y=290)
l=Label(f1,font=('Times New Roman',20,'bold italic'),text='Start the Training Using Perceptron Network',fg='green',bd=10,anchor='w',bg='black')
l.place(x=5,y=330)
f2=Frame(f1,width=400,height=80,relief='sunken',bg='white')
f2.place(x=200,y=390)
def trained():
    tw=Tk()
    tw.title("Perceptron")
    tw.geometry('1350x750+0+0')
    tw.config(bg="DeepSkyBlue")
    l=Label(tw,font=('Times New Roman',30,'bold italic'),text="Results after Training the network",fg='black',bd=10,anchor='w',bg='DeepSkyBlue')
    l.place(x=300,y=30)
    l=Label(tw,font=('Times New Roman',30,'bold italic'),text="     with Perceptron Network      ",fg='black',bd=10,anchor='w',bg='DeepSkyBlue')
    l.place(x=300,y=90)
    with open("PerceptronData.txt","r") as fp:
        data=fp.readlines()
    a=[]
    j=0
    for i in data:
        a.append(i.strip())

    f2=Frame(tw,width=600,height=500,relief='sunken',bg='DeepSkyBlue')
    f2.place(x=300,y=160)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[0],fg='black',bd=10,anchor='w',bg='DeepSkyBlue')
    l.place(x=5,y=30)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[1],fg='black',bd=10,anchor='w',bg='DeepSkyblue')
    l.place(x=5,y=70)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[5],fg='black',bd=10,anchor='w',bg='DeepSkyblue')
    l.place(x=5,y=110)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[6],fg='black',bd=10,anchor='w',bg='DeepSkyblue')
    l.place(x=5,y=150)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[7],fg='black',bd=10,anchor='w',bg='DeepSkyblue')
    l.place(x=5,y=190)
    l=Label(f2,font=('Times New Roman',20,'bold italic'),text=a[8],fg='black',bd=10,anchor='w',bg='DeepSkyblue')
    l.place(x=5,y=230)
    l=Label(tw,font=('Times New Roman',20,'bold italic'),text="Check with User inputs",fg='blue',bd=10,anchor='w')
    l.place(x=130,y=450)
    btnl=Button(tw,text='Check', width=10,font=('arial',20,'bold'),bg='black',fg='white',relief='groove',command=trained)
    btnl.place(x=150,y=510)
    btnl=Button(tw,text='Back', width=10,font=('arial',20,'bold'),bg='black',fg='white',relief='groove',command=trained)
    btnl.place(x=750,y=510)
btnl=Button(f2,text='Start Training', width=15,font=('arial',20,'bold'),bg='black',fg='white',relief='raised',command=trained)
btnl.place(x=60,y=15)
pw.mainloop()
